### PR TITLE
Fix PHP8.1 tentative return types

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes the notices found in https://github.com/bytestream/Imap_Client/pull/3.

Upstream PR: https://github.com/horde/Mime/pull/4

### CODE REVIEW

**Comment by ChristophWurst** [comment]
cc @bytestream :)

**Comment by bytestream** [comment]
This looks like a missed case:
```
PHP Deprecated:  Return type of Horde_Mime_Part_Iterator::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Part/Iterator.php on line 65
PHP Deprecated:  Return type of Horde_Mime_Part_Iterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Part/Iterator.php on line 74
PHP Deprecated:  Return type of Horde_Mime_Part_Iterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Part/Iterator.php on line 92
PHP Deprecated:  Return type of Horde_Mime_Part_Iterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Part/Iterator.php on line 83
PHP Deprecated:  Return type of Horde_Mime_Part_Iterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Part/Iterator.php on line 132
PHP Deprecated:  Return type of Horde_Mime_Part_Iterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Part/Iterator.php on line 118
```

**Comment by bytestream** [comment]
Also
```
PHP Deprecated:  Return type of Horde_Mime_Filter_Encoding::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Filter/Encoding.php on line 47
PHP Deprecated:  Return type of Horde_Mime_Filter_Encoding::onCreate() should either be compatible with php_user_filter::onCreate(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Filter/Encoding.php on line 37
```

**Comment by ChristophWurst** [comment]
``horde-stream-filter`` is the next repo to tackle :smiling_imp:

**Comment by bytestream** [comment]
One more in here :upside_down_face: 
```
PHP Deprecated:  Return type of Horde_Mime_Uudecode::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/Mime/Mime/lib/Horde/Mime/Uudecode.php on line 117
```

**Comment by bytestream** [comment]
Thanks man :)

**Pull request merged**
